# tag::oauth[]
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 76769redactedoogleusercontent.com
            client-secret: ovj6b_va5fEB-EWEcE3FGOK6
# end::oauth[]
  mvc:
    hiddenmethod:
      filter:
        enabled: true
